### ISSUE TITLE
Memory Database file cannot be read error

### ISSUE THREAD

**Issue by Alexwhite3000** [tbroyer/gwt-maven-archetypes#36]
This was working fine yesterday, and then I just started getting this. git reports no changes to any sensitive files in my proj. I tried putting a tomcat-users.xml into server/src/main/tomcatconf but that didnt get copied over. Any thoughts?

```shell
$mvn tomcat7:run -pl *-server -am -Denv=dev -Dgwt.logLevel=INFO
 
[ERROR] Failed to execute goal org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:run (default-cli)
 on project mailapp-server: Could not start Tomcat: Failed to start component [StandardServer[-1]]:
 Failed to start component [StandardService[Tomcat]]: Failed to start component 
[StandardEngine[Tomcat]]: Failed to start component [Realm[MemoryRealm]]: Memory database file
 /home/alex/workspace/cupofjoe/cupofjoe-server/target/tomcat/conf/tomcat-users.xml cannot be read ->
 [Help 1]

```

**Comment by tbroyer** [comment]
If it worked yesterday and it no longer works today, and this is in the same project, then it's not related to the archetype. If you made a new project from the archetype today and it doesn't work, but still works in another project created yesterday, then it could have been the archetype, but it can't because it hasn't changed since yesterday.

I'm afraid I can't really help. Ask the Tomcat plugin team.
(as a rule of thumb, please ask for help on StackOverflow before creating an issue)

**Comment by fedecz** [comment]
Hi there, I'm having the same problem...any ideas?? thanks

**Comment by tbroyer** [comment]
I tried with:

```
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)
Maven home: …/apache-maven-3.0.5
Java version: 1.8.0_45-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-16-generic", arch: "amd64", family: "unix"
```

and

```
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T21:10:27+01:00)
Maven home: …/apache-maven-3.3.1
Java version: 1.8.0_45-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-16-generic", arch: "amd64", family: "unix"
```

and couldn't reproduce the problem; it just works.

Steps:

* `mvn archetype:generate …` (ok, to be fair, I actually ran `mvn verify` on the project and then went to `guice-rf-activities/target/test-classes/projects/basic/project/basic` and ran an `mvn clean` there)
* `mvn tomcat7:run -pl *-server -am -Denv=dev`
* open `http://localhost:8080/` in my browser; it correctly shows the login page, and upon login shows a 500 error because the JSP page cannot find the `basic.nocache.js` (this is expected as I neither launched the SuperDevMode nor compiled the `*-client` project)

**Comment by mitchhf** [comment]
Had the same problem recently and a `mvn clean` did the trick.
