### ISSUE TITLE
DependencyResolutionException Could not find artifact ...-shared:jar

### ISSUE THREAD

**Issue by joelhandwell** [tbroyer/gwt-maven-archetypes#38]
Hello, I got following error while start to use this archetype.

```
C:\Users\Joel\Codes\gsp\globalsp\globalsp-server>mvn jetty:start -Denv=dev
[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.3.2/exec-maven-plugin-1.3.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.3.2/exec-maven-plugin-1.3.2.pom (12 KB at 17.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/33/mojo-parent-33.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/33/mojo-parent-33.pom (26 KB at 163.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom (5 KB at 74.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.3.2/exec-maven-plugin-1.3.2.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/exec-maven-plugin/1.3.2/exec-maven-plugin-1.3.2.jar (46 KB at 290.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.2/maven-war-plugin-2.2.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.2/maven-war-plugin-2.2.pom (7 KB at 101.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.2/maven-war-plugin-2.2.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/2.2/maven-war-plugin-2.2.jar (77 KB at 817.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.pom (11 KB at 93.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.12.4/surefire-2.12.4.pom (14 KB at 217.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.12.4/maven-surefire-plugin-2.12.4.jar (30 KB at 238.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.2.3.v20140905/jetty-maven-plugin-9.2.3.v20140905.pom
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.2.3.v20140905/jetty-maven-plugin-9.2.3.v20140905.pom (6 KB at 56.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-project/9.2.3.v20140905/jetty-project-9.2.3.v20140905.pom
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-project/9.2.3.v20140905/jetty-project-9.2.3.v20140905.pom (33 KB at 205.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-parent/22/jetty-parent-22.pom
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-parent/22/jetty-parent-22.pom (22 KB at 278.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.2.3.v20140905/jetty-maven-plugin-9.2.3.v20140905.jar
Downloaded: https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-maven-plugin/9.2.3.v20140905/jetty-maven-plugin-9.2.3.v20140905.jar (95 KB at 861.6 KB/sec)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building globalsp-server 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:9.2.3.v20140905:start (default-cli) > validate @ globalsp-server >>>
[INFO]
[INFO] <<< jetty-maven-plugin:9.2.3.v20140905:start (default-cli) < validate @ globalsp-server <<<
[WARNING] The POM for com.github.globalsp:globalsp-shared:jar:1.0-SNAPSHOT is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/com/google/web/bindery/requestfactory-apt/2.7.0/requestfactory-apt-2.7.0.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/web/bindery/requestfactory-apt/2.7.0/requestfactory-apt-2.7.0.pom (611 B at 6.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/web/bindery/requestfactory-server/2.7.0/requestfactory-server-2.7.0.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/web/bindery/requestfactory-server/2.7.0/requestfactory-server-2.7.0.pom (796 B at 10.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/inject/extensions/guice-jndi/4.0-beta5/guice-jndi-4.0-beta5.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/inject/extensions/guice-jndi/4.0-beta5/guice-jndi-4.0-beta5.pom (535 B at 6.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/inject/extensions/guice-servlet/4.0-beta5/guice-servlet-4.0-beta5.pom
Downloaded: https://repo.maven.apache.org/maven2/com/google/inject/extensions/guice-servlet/4.0-beta5/guice-servlet-4.0-beta5.pom (921 B at 11.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.pom
Downloaded: https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.pom (13 KB at 131.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/net/java/jvnet-parent/1/jvnet-parent-1.pom
Downloaded: https://repo.maven.apache.org/maven2/net/java/jvnet-parent/1/jvnet-parent-1.pom (5 KB at 19.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/google/web/bindery/requestfactory-apt/2.7.0/requestfactory-apt-2.7.0.jar
Downloading: https://repo.maven.apache.org/maven2/com/google/inject/extensions/guice-servlet/4.0-beta5/guice-servlet-4.0-beta5.jar
Downloading: https://repo.maven.apache.org/maven2/com/google/inject/extensions/guice-jndi/4.0-beta5/guice-jndi-4.0-beta5.jar
Downloading: https://repo.maven.apache.org/maven2/com/google/web/bindery/requestfactory-server/2.7.0/requestfactory-server-2.7.0.jar
Downloading: https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/google/inject/extensions/guice-servlet/4.0-beta5/guice-servlet-4.0-beta5.jar (75 KB at 478.1 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/com/google/inject/extensions/guice-jndi/4.0-beta5/guice-jndi-4.0-beta5.jar (8 KB at 42.0 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/com/google/web/bindery/requestfactory-apt/2.7.0/requestfactory-apt-2.7.0.jar (89 KB at 437.7 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar (84 KB at 380.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/com/google/web/bindery/requestfactory-server/2.7.0/requestfactory-server-2.7.0.jar (1860 KB at 1803.4 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.485 s
[INFO] Finished at: 2015-08-04T20:28:13-04:00
[INFO] Final Memory: 17M/371M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project globalsp-server: Could not resolve dependencies for project com.github.globalsp:globalsp-server:war:1.0-SNAPSHOT: Could not find artifact com.github.globalsp:globalsp-shared:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

What I did before this is, 
- generate archtype:

```
mvn archetype:generate \
   -DarchetypeCatalog=https://oss.sonatype.org/content/repositories/snapshots/ \
   -DarchetypeGroupId=net.ltgt.gwt.archetypes \
   -DarchetypeArtifactId=guice-rf-activities \
   -DarchetypeVersion=1.0-SNAPSHOT
```
- start code server: 

```
mvn gwt:codeserver -pl globalsp-client -am
```

My maven version is 3.3.3, running on Windows 10, JDK is build 1.8.0_51-b16

Is there anything I missed? Or any other person encounter same error?
I guess it's related to shared code, but not sure how to dig in more.

**Comment by tbroyer** [comment]
Did you `mvn install`?

**Comment by freddyboucher** [comment]
Hi @tbroyer 
I'm facing a similar problem.

1. I built a new project with your artifact
2. I executed `mvn clean package` (generally I prefer calling `package` than `install` so that I'm sure my local dev env don't use a not up-to-date jar in **.m2/repository/** instead of the source)
3. `mvn tomcat7:run -pl *-server -am -Denv=dev` works perfectly.
4. I wanted to try `mvn jetty:start -Denv=dev` (in my **\*-server/** folder) but I got:

```log
➜  webapp-server git:(master) ✗ mvn jetty:start -Denv=dev
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building webapp-server 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> jetty-maven-plugin:9.2.3.v20140905:start (default-cli) > validate @ webapp-server >>>
[INFO] 
[INFO] <<< jetty-maven-plugin:9.2.3.v20140905:start (default-cli) < validate @ webapp-server <<<
[WARNING] The POM for com.test:webapp-shared:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.889 s
[INFO] Finished at: 2016-03-12T16:38:28+11:00
[INFO] Final Memory: 13M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project webapp-server: Could not resolve dependencies for project com.test:webapp-server:war:1.0-SNAPSHOT: Could not find artifact com.test:webapp-shared:jar:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Mav en using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

But then I execute `mvn clean install` as you recommended in this post and it works!

But does it mean it uses the **jar** in my **.m2/repository/** instead of the real source? In other words, if I do some changes in the shared module, do I need to execute `mvn clean install`?

Thanks

**Comment by tbroyer** [comment]
> generally I prefer calling `package` than `install` so that I'm sure my local dev env don't use a not up-to-date jar in *.m2/repository/* instead of the source

Indeed, `install` is an anti-pattern (it has its use-cases, but it should be the exception rather than the norm; you can read more about it over on my blog –[here](http://blog.ltgt.net/in-quest-of-the-ultimate-build-tool) and [here](http://blog.ltgt.net/maven-is-broken-by-design)and [Lex Spoon's blog](http://blog.lexspoon.org/2012/12/recursive-maven-considered-harmful.html) [[archive](https://web.archive.org/web/20150928131855/http://blog.lexspoon.org/2012/12/recursive-maven-considered-harmful.html)); though I'd say you generally want to _replace_ it with `verify`, which will run integration tests too, rather than `package`.

> But then I executed `mvn clean install` as you recommended in this post and it works!

This is because you're running the goal from the `webapp-server` folder, i.e. bypassing the reactor build, and you cannot run it at the reactor level because the `jetty-maven-plugin` doesn't have built-in support for reactor builds, contrary to the Apache Tomcat Maven Plugins; see http://jetty.4.x6.nabble.com/jira-JETTY-1517-Resolve-submodule-artifacts-in-reactor-builds-with-Maven-3-td4958468.html (never moved to the new issue tracker after transferred to the Jetty project proper and shutdown of CodeHaus; feel free to report it back again).
Actually, it is possible to run `jetty:run` at the reactor level, but it requires configuring the plugin to `<skip>true</skip>` in every module (except of course in the `*-server` one). This adds bloat to the POMs. I've had a local branch for that for years actually (my commit dates back to September 2012), I might revive it and merge it.

**Comment by tbroyer** [comment]
Sorry, forgot to answer your last question:

> But does it mean it uses the **jar** in my **.m2/repository/** instead of the real source? In other words, if I do some changes in the shared module, do I need to execute `mvn clean install`?

It'll load both. The JAR will be loaded from the local repository due to normal Maven resolution and how its used by the `jetty-maven-plugin`, and the `webapp-shared/target/classes/` will be loaded through the `extraClasspath` configuration (in the `env-dev` profile). The `extraClasspath` comes first in the webapp classloader, so it has precedence over the installed JAR. That means you only need to `mvn install` once, but you may want to do it regularly if you make big changes to the shared module (BTW, you only need to install the dependencies of the server module; in the archetype that means only the shared module actually, so `mvn install -pl webapp-shared` should be enough)

**Comment by freddyboucher** [comment]
Thanks @tbroyer 
Unfortunately I can't use **extraClasspath**.
My project is an **App Engine** project so I don't use **jetty-maven-plugin**, **tomcat6-maven-plugin** neither **tomcat7-maven-plugin** but **appengine-maven-plugin**

And I'm limited to **servlet-api** 2.5.

Anyway I made my project works perfectly with your plugin!

I will update an old [proof of concept project](https://github.com/freddyboucher/gwt-storage-objectify) made with **GWT**, **App Engine**, **Objectify**, **gwt-storage** with your plugin too and I would appreciate your feedback.

Thanks

**Comment by tbroyer** [comment]
Great! Keep me informed when you have something online. Maybe we could add a new archetype for app-engine then?

Note that one possibility I haven't explored yet would be to re-package the app (with the dev profile so you skip the client code) whenever you change a shared class. And whenever adding new "web resource roots" (the `<baseResource>`, `<resourceAsCsv>` in the jetty-maven-plugin; the `extraResourcePaths` in the `src/main/tomcatconf/context.xml` for Tomcat) is not possible, one could either change the `launcherDir` to point to the server module's output (not great: you risk deploying a dev version if you forget to `mvn clean`), or package the webapp to a specific folder used as `launcherDir`. The limitation in both cases is that you need to repackage the webapp whenever you make a change; I suppose this might already be the case with the appengine-maven-plugin.

**Comment by freddyboucher** [comment]
Hi @tbroyer 
Sorry for the delay but here it comes: https://github.com/freddyboucher/gwt-storage-objectify
It would be awesome and probably really helpful for many developers to provide an archetype for App Engine.

**Comment by skabashnyuk** [comment]
I think this issue may be related to the fact that latest archetype plugin
doesn't support   ``` -DarchetypeCatalog=https://oss.sonatype.org/content/repositories/snapshots/ \
   -DarchetypeGroupId=net.ltgt.gwt.archetypes \```

**Comment by dmg46664** [comment]
@tbroyer , @freddyboucher  - Thank you for the thread guys!

I've found this thread most helpful. Ran into the same `mvn install` problems needing jetty for GAE.

There is a lot of old data hanging around. I had to struggle [through the previous mojo build](https://github.com/davidbuhler/maven-gwt-appengine-jdo-seed-project) because the seed project I found looked like it had GWT and GAE successfully integrated. Then try and upgrade to 2.8.0 because vaadin polymer elements needs that. Then I [ran into further issues around debugging that](https://github.com/vaadin/gwt-polymer-elements/issues/148) and having found out that Mojo was deprecated, I thought I'd give this route a try giving it is more supported.

@tbroyer - I'm happy to help copy much of this thread to the wikis, to tidy this issue up in order to close it, if you're happy with that?
@freddyboucher - Hopefully your gwt-storage-objectify project works so I can get an GAE / GWT project off the ground. I guess there's no reason a good GAE & GWT archetype can't live elsewhere.

**Comment by dmg46664** [comment]
Worked perfectly with the new gwt-maven-plugin and @freddyboucher 's sample project. I've upgraded it to 2.8.0 and created a PR.

Thanks!

**Comment by tbroyer** [comment]
FWIW, the `mvn install` instructions were (erroneously) removed (rather than adapted) when I switched to `net.ltgt.gwt.maven:gwt-maven-plugin` 2 years ago (in b3ef2b90f3435323c9aef0a0ba93677a98b0e5b9). I just reintroduced some wording in 2555d13, scoped to Jetty only.

**Comment by Armen-e5518** [comment]
You must delete the project files that are duplicated.
Ex. ***(1).xml. 
and then 
-mvn clean install
